package exception;

public class Ex02 {

	public static void main(String[] args) {
		
		try {
			System.out.println(1 / 0); // 0으로 나누기 금지
			System.out.println("예외가 발생하면 실행 안됨");
		}catch(ArithmeticException ae) {
			System.out.println("예외가 발생!!");
			
		}catch(Exception e) { //다중 catch 가능
			// ArithmeticException을 제외한 모든 예외처리
			// Exception은 모든 예외를 처리할 수 있다.
			// 제일 마지막에 와야 한다!
			System.out.println("Exception 예외발생");
		}

	}

}
